# Generated by Django 3.1 on 2020-09-07 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('channel_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('channel_nm', models.CharField(max_length=200)),
                ('thumbnails_url', models.CharField(max_length=3000, null=True)),
                ('reg_datetime', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'channel',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('foreign_id', models.CharField(max_length=200)),
                ('comment', models.CharField(max_length=1000)),
                ('reg_datetime', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('video_nm', models.CharField(max_length=200)),
                ('thumbnails_url', models.CharField(max_length=3000, null=True)),
                ('reg_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('channel_id', models.ForeignKey(db_column='channel_id', on_delete=django.db.models.deletion.CASCADE, to='jack.channel')),
            ],
            options={
                'db_table': 'video',
            },
        ),
    ]
