# Generated by Django 3.1 on 2020-08-30 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jack', '0003_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='channel',
            new_name='channel_id',
        ),
    ]
