# Generated by Django 3.1 on 2020-08-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jack', '0004_auto_20200830_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('foreign_id', models.CharField(max_length=200)),
                ('comment', models.CharField(max_length=1000)),
                ('reg_datetime', models.DateTimeField()),
            ],
        ),
    ]
