# Generated by Django 3.1 on 2020-09-06 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jack', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='reg_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='thumbnails',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='reg_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnails_url',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='video_nm',
            field=models.CharField(default='マイグレーシ用の動画名', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='reg_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
