# Generated by Django 3.1 on 2020-09-06 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jack', '0006_auto_20200906_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='thumbnails',
            new_name='thumbnails_url',
        ),
    ]
