# Generated by Django 3.1 on 2020-08-25 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choie_text',
            new_name='choice_text',
        ),
    ]
